---
- name: Configure lab instance
  hosts: all
  become: true
  tasks:
    - name: Download zombie binary
      get_url:
        url: "https://github.com/arlcrow/zombies-lab/releases/latest/download/zombie"
        dest: "/home/ubuntu/.local/zombie"
        mode: '0755'
    - name: Run zombies (3 times)
      shell: |
        for i in {1..3}; do
          /home/ubuntu/.local/zombie &
          sleep 2
        done
      async: 0
      poll: 0
