name: API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: |
        cd ./api
        go mod tidy

    - name: Build
      run: |
        cd ./api
        go build -v ./main.go -o ./api

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        path: ./api/api
