name: API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Verify dependencies
      run: |
        cd ./api
        go mod verify
        
    - name: Build
      run: |
        cd ./api
        go build -v -o api

    - name: Run tests
      run: |
        cd ./api
        go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-binary
        path: api/api
        retention-days: 5
