name: Zombie

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        path: zombie
